# Use the official MySQL image
FROM mysql:8.0.30

# Environment variables for MySQL database configuration
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=url_shortner
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=kapil1234

# Copy the SQL script to initialize the database
COPY init.sql /docker-entrypoint-initdb.d/

